name: build
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pytest
        env:
          QNS_LOGLVL: DEBUG
    timeout-minutes: 30
